# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-30 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='cellphone',
            field=models.IntegerField(default=0),
        ),
    ]
