# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-30 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0002_auto_20160530_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='cellphone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
