# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-19 16:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routes', '0002_auto_20160619_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='contact',
        ),
        migrations.AddField(
            model_name='route',
            name='user_contact',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='route_user_contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
