# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-19 16:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routes', '0003_auto_20160619_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='user_contact',
        ),
        migrations.AddField(
            model_name='route',
            name='contact',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='route_contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
